nginx:
  build: frontend/webservernginx
  links:
    - mariadb:mysql
    - memcached:memcached
    - redis:redis
  ports:
    - "8081:80"
    - "443:443"
  volumes:
    - $CODEPATH:/home/www
mariadb:
  image: mariadb
  ports:
    - "3306:3306"
  volumes:
    - ./log/mariadb:/var/log/mysql
    - ./data/mariadb:/var/lib/mysql
    - ./mariadbserver/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  environment:
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_USER: $MYSQL_USER
    MYSQL_PASSWORD: $MYSQL_PASSWORD
memcached:
  image: memcached
  ports:
    - "11211:11211"
redis:
  image: redis
  volumes:
   - ./data/redis:/data
  ports:
    - "6379:6379"
